<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'localduplibase');
define('_DB_USER_', 'LocalDupliBase');
define('_DB_PASSWD_', 'Bcomm62000');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'U8CA8CsZ6RruBL0xiASgIAwT9AWbjWyoj0j3pSJBhDtrCJ0yM44eJ4Ko');
define('_COOKIE_IV_', 'mJ9UHuSE');
define('_PS_CREATION_DATE_', '2014-06-30');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.8');
define('_RIJNDAEL_KEY_', '0Jo6jwDv4y6NmQVXzOvtXbFtO62B0e8Y');
define('_RIJNDAEL_IV_', 'T43Km9q4atD3yt7Bj0zRtQ==');
